version: '3.2'

services:
  resurface:
    image: resurfaceio/resurface:3.1.17
    container_name: mux_resurface
    ports:
        - '7700:7700'
        - '7701:7701'
      
  mux:
    image: test-mux
    container_name: mux
    ports:
      - '80:5000'
    env_file:
      - src/.env

#     - 'host:container'
