// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AllNews struct {
	News *News `json:"news"`
}

type News struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Body  string `json:"body"`
}

type Ok struct {
	Ok bool `json:"ok"`
}
